/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import dao.CarroDao;
import dao.InstanceDao;
import dao.LocadoraDao;
import dao.MotoDao;
import design.DesignApp;
import idioma.IdiomaApp;
import java.awt.event.FocusListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import listener.TipNoFocus;
import modelos.Locadora;
import validadores.Validador;

/**
 *
 * @author Isaac
 */
public class LocadoraEditLoc extends javax.swing.JFrame
    implements FrameTheme, WindowListener, FrameLang {
    
    private LocadoraDao locadoraDao = InstanceDao.LOCADORA_DAO;
    private CarroDao carroDao = InstanceDao.CARRO_DAO;
    private MotoDao motoDao = InstanceDao.MOTO_DAO;
    private Locadora locadoraAtual; //locadora add na classe anterior pelo addLocadora - locator added in the ancient class
//    private Locadora locadoraAtual = locadoraDao.get(1L) ; //to test
    /**
     * Creates new form LocadoraEditLoc
     */
    public LocadoraEditLoc() {
        initComponents();
       // extraConfigs(); //chama em addlocadora
       addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnCampos = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FastVehicles | Editar Locadora");

        pnCampos.setToolTipText("");

        lblNome.setText("Nome");

        txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNome.setToolTipText("Digite o nome da locadora\"");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone");

        txtTelefone.setToolTipText("Digite o telefone da locadora");

        lblEmail.setText("Email");

        txtEmail.setToolTipText("Digite o e-mail  da locadora");

        lblEndereco.setText("Endereço");

        txtEndereco.setToolTipText("Digite o endereço  da locadora");
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        lblCnpj.setText("CNPJ");

        txtCnpj.setToolTipText("Digite o CNPJ da locadora");
        txtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCamposLayout = new javax.swing.GroupLayout(pnCampos);
        pnCampos.setLayout(pnCamposLayout);
        pnCamposLayout.setHorizontalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCnpj)
                .addGap(27, 27, 27)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnCamposLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnCamposLayout.createSequentialGroup()
                            .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTelefone)
                                .addComponent(lblEmail)
                                .addComponent(lblEndereco))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEndereco)))
                        .addComponent(lblNome))
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        pnCamposLayout.setVerticalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCnpj))
                .addGap(45, 45, 45))
            .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnCamposLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefone)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEndereco))
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar dados");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pnCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!placeholderOrEmpty(txtNome) && Validador.nomeCerto(txtNome.getText().trim())) { //se o nome n esta vazio e bate com as exigencias
            if(!placeholderOrEmpty(txtTelefone) && Validador.telefoneCerto(txtTelefone.getText().trim())) {
                if(!placeholderOrEmpty(txtEmail) && Validador.emailCerto(txtEmail.getText().trim())) {
                    if(!placeholderOrEmpty(txtEndereco)) {
                        if(!placeholderOrEmpty(txtCnpj) && Validador.cnpjCerto(txtCnpj.getText().trim())) {

                            //edita objeto carro
                            locadoraAtual.setNome(txtNome.getText().trim());
                            locadoraAtual.setTelefone(txtTelefone.getText().trim());
                            locadoraAtual.setEmail(txtEmail.getText().trim());
                            locadoraAtual.setEndereco(txtEndereco.getText().trim()) ;
                            locadoraAtual.setCnpj(txtCnpj.getText().trim());

                            locadoraDao.update(locadoraAtual, null); //atualiza no bd
                            

                            //mensagem de cadastro com sucesso
                            URL url = getClass().getResource("/images/success.png");
                            ImageIcon sucessIcon = new ImageIcon(url);
                            if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) {
                                JOptionPane.showMessageDialog(this, "Locadora editada com sucesso!",
                                    "Locadora Editada!", JOptionPane.PLAIN_MESSAGE, sucessIcon);
                            }else if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
                                JOptionPane.showMessageDialog(this, "Locator successfully edited!",
                                    "Locator Edited!", JOptionPane.PLAIN_MESSAGE, sucessIcon);
                            }   
                            

                
                        }else {
                            
                            if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) {
                                JOptionPane.showMessageDialog(this, "Erro no CNPJ da locadora:"
                                        + "\n- Verifique se o campo está vazio;"
                                        + "\n- Digite o CNPJ com apenas números.",
                                        "Erro no CNPJ da Locadora", JOptionPane.ERROR_MESSAGE);
                            }else if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
                                JOptionPane.showMessageDialog(this, "CNPJ locator error:"
                                    + "\n- Verify if field is empty;"
                                    + "\n- Type CNPJ with numbers only.",
                                    "CNPJ Locator Error", JOptionPane.ERROR_MESSAGE);
                            }
                            

                        }
                                                
                    }else {
                        
                        if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) {
                            JOptionPane.showMessageDialog(this, "Preencha o endereço!",
                                "Endereço Vazio!", JOptionPane.ERROR_MESSAGE);
                        }else if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
                            JOptionPane.showMessageDialog(this, "Fill out locator address!",
                                "Empty Address!", JOptionPane.ERROR_MESSAGE);
                        }
                        

                    }
                    
                }else {
                    
                    if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) { 
                        JOptionPane.showMessageDialog(this, "Erro no e-mail da locadora:"
                            + "\n- Verifique se o campo está vazio;"
                            + "\n- Verifique se o e-mail está correto",
                            "Erro no E-mail da Locadora", JOptionPane.ERROR_MESSAGE); 
                    }else if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {                                           
                        JOptionPane.showMessageDialog(this, "Locator email error:"
                            + "\n- Verify if field is empty;"
                            + "\n- Verify if email is correct;",
                            "Locator Email Error", JOptionPane.ERROR_MESSAGE); 
                    }
   
                }
            }else {
                
                if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) {
                    JOptionPane.showMessageDialog(this, "Erro no telefone da locadora:"
                        + "\n- Verifique se o campo está vazio;"
                        + "\n- Preencha o telefone com apenas números. Ex.: 61981828182",
                        "Erro no Telefone da Locadora", JOptionPane.ERROR_MESSAGE);
                }else if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
                    JOptionPane.showMessageDialog(this, "Phone locator error:"
                        + "\n- Verify if field is empty;"
                        + "\n- Fill out phone with numbers only. Like: 61981828182",
                        "Phone Locator Error", JOptionPane.ERROR_MESSAGE);
                }
                

           }

        }else {
            
            if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) {
                JOptionPane.showMessageDialog(this, "Erro no nome da locadora:"
                    + "\n- Verifique se o campo está vazio;"
                    + "\n- O nome deve conter somente letras e espaços não duplicados;"
                    + "\n- Verifique se o nome possui espaços duplicados, deixe apenas um.",
                    "Erro no Nome da Locadora", JOptionPane.ERROR_MESSAGE);
            }else if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
                JOptionPane.showMessageDialog(this, "Locator name error:"
                    + "\n- Verify if field is empty;"
                    + "\n- Name must have letters and nonduplicated whitespaces only;"
                    + "\n- Use just one whitespace per word. Like: My Locator Name",
                    "Locator Name Error", JOptionPane.ERROR_MESSAGE);
            }
            

        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    public void extraConfigs() {
          
        //configs do frame - frames config
        setLocationRelativeTo(null); //configs do frame - frames config
        //coloca icone no jframe - insert icon on jframe
        URL url = getClass().getResource("/images/car-default-img.png");
        if(!(url == null)) {
            setIconImage(new ImageIcon(url).getImage());
        }
        
        //modificacoes gerais - general changes
        lblNome.setFont(DesignApp.fonteGeral);
        lblTelefone.setFont(DesignApp.fonteGeral);
        lblEmail.setFont(DesignApp.fonteGeral);
        lblEndereco.setFont(DesignApp.fonteGeral);
        lblCnpj.setFont(DesignApp.fonteGeral);

        txtNome.setFont(DesignApp.fonteGeral);
        txtNome.addFocusListener(new TipNoFocus(txtNome, "Ex.: Mario Ferreira",
               DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        
        txtTelefone.setFont(DesignApp.fonteGeral);
        txtTelefone.addFocusListener(new TipNoFocus(txtTelefone,
                "Ex.: (61)99090-9090",
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        txtEmail.setFont(DesignApp.fonteGeral);
        txtEmail.addFocusListener(new TipNoFocus(txtEmail, 
                "Ex.: mail@mail.com",
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        txtEndereco.setFont(DesignApp.fonteGeral);
        txtEndereco.addFocusListener(new TipNoFocus(txtEndereco, 
                "Ex.: RIACHO FUNDO 2, QN 0B CJ 00 LT 0", 
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        txtCnpj.setFont(DesignApp.fonteGeral);
        txtCnpj.addFocusListener(new TipNoFocus(txtCnpj, 
                "Ex.: 12341234123412",
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        
        txtNome.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtTelefone.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtEmail.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtEndereco.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtCnpj.setForeground(DesignApp.FIELD_FONT_COLOR);
        
        txtNome.setText(locadoraAtual.getNome());
        txtTelefone.setText(locadoraAtual.getTelefone());
        txtEmail.setText(locadoraAtual.getEmail());
        txtEndereco.setText(locadoraAtual.getEndereco());
        txtCnpj.setText(locadoraAtual.getCnpj());
        
          //update lang
        if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
            updateLangComponents();
        }
        
    }
    
    public void addLocadora(Locadora loc) {
        locadoraAtual = loc;
        extraConfigs();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocadoraEditLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocadoraEditLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocadoraEditLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocadoraEditLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocadoraEditLoc().setVisible(true);
            }
        });
    }

    public boolean placeholderOrEmpty(JTextField comp) { //verifica se campo tem texto de exemplo padrao
        return comp.getForeground() == DesignApp.FIELD_FONT_TIP_COLOR
            || comp.getText().trim().isEmpty();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnCampos;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    @Override
    public void resetaListenerCampos() {
        txtNome.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtCnpj.setText("");
        txtNome.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtTelefone.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtEmail.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtEndereco.setForeground(DesignApp.FIELD_FONT_COLOR);
        txtCnpj.setForeground(DesignApp.FIELD_FONT_COLOR);
        
        for(FocusListener focus: txtNome.getFocusListeners()) { //percorre listeneers
            txtNome.removeFocusListener(focus);//remove focus listeners
        }

        for(FocusListener focus: txtTelefone.getFocusListeners()) { //percorre listeneers
            txtTelefone.removeFocusListener(focus);//remove focus listeners
        }
        
        for(FocusListener focus: txtEmail.getFocusListeners()) { //percorre listeneers
            txtEmail.removeFocusListener(focus);//remove focus listeners
        }
        
        for(FocusListener focus: txtEndereco.getFocusListeners()) { //percorre listeneers
            txtEndereco.removeFocusListener(focus);//remove focus listeners
        }
        
        for(FocusListener focus: txtCnpj.getFocusListeners()) { //percorre listeneers
            txtCnpj.removeFocusListener(focus);//remove focus listeners
        }
        
        txtNome.addFocusListener(new TipNoFocus(txtNome, "Ex.: Mario Ferreira",
               DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        
        txtTelefone.setFont(DesignApp.fonteGeral);
        txtTelefone.addFocusListener(new TipNoFocus(txtTelefone,
                "Ex.: (61)99090-9090",
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        txtEmail.setFont(DesignApp.fonteGeral);
        txtEmail.addFocusListener(new TipNoFocus(txtEmail, 
                "Ex.: mail@mail.com",
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        txtEndereco.setFont(DesignApp.fonteGeral);
        txtEndereco.addFocusListener(new TipNoFocus(txtEndereco, 
                "Ex.: RIACHO FUNDO 2, QN 0B CJ 00 LT 0", 
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));
        txtCnpj.setFont(DesignApp.fonteGeral);
        txtCnpj.addFocusListener(new TipNoFocus(txtCnpj, 
                "Ex.: 12341234123412",
                DesignApp.FIELD_FONT_COLOR,
                DesignApp.FIELD_FONT_TIP_COLOR, 0));

    }
    
     //window listener
    @Override
    public void windowOpened(WindowEvent e) {
        InstanceFrame.addFrame(this); //adiciona frame na lista de frames abertos
    }

    @Override
    public void windowClosing(WindowEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        InstanceFrame.removeFrame(this); //remove frame
    }

    @Override
    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
        //update lang method
    @Override
    public void updateLangComponents() {
        
        if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) { //se idioma eh ingles
	    setTitle("FastVehicles | Edit Locator");
            lblNome.setText("Name");
            lblTelefone.setText("Phone");
            lblEndereco.setText("Address");
            
            btnSalvar.setText("Save");
            
            txtNome.setToolTipText("Type locator name");
            txtTelefone.setToolTipText("Type locator phone");
            txtEmail.setToolTipText("Type locator email");
            txtEndereco.setToolTipText("Type locator address");
            txtCnpj.setToolTipText("Type locator CNPJ");
            btnSalvar.setToolTipText("Save data");
            
	}else if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) { //se for portugues
            setTitle("FastVehicles | Editar Locadora");
            lblNome.setText("Nome");
            lblTelefone.setText("Telefone");
            lblEndereco.setText("Endereço");
            
            btnSalvar.setText("Salvar");
            
            txtNome.setToolTipText("Digite o nome da locadora");
            txtTelefone.setToolTipText("Digite o telefone da locadora");
            txtEmail.setToolTipText("Digite o e-mail da locadora");
            txtEndereco.setToolTipText("Digite o endereço da locadora");
            txtCnpj.setToolTipText("Digite o CNPJ da locadora");
            btnSalvar.setToolTipText("Salvar dados");
            
	}
    }
    
}
