/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import dao.InstanceDao;
import dao.LocacaoCarroDao;
import dao.LocadoraDao;
import design.DesignApp;
import idioma.IdiomaApp;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import modelos.Locacao;
import modelos.Veiculo;

/**
 *
 * @author Isaac
 */
public class VerDadosLocadoraLocacao extends javax.swing.JFrame 
    implements FrameTheme, WindowListener, FrameLang {
    
    private LocacaoCarroDao locacaoCarroDao = InstanceDao.LOCACAO_CARRO_DAO;
    private LocadoraDao locadoraDao = InstanceDao.LOCADORA_DAO;
    private Locacao locacaoAtual;
    /**
     * Creates new form VerDadosLocadoraLocacao
     */
    public VerDadosLocadoraLocacao() {
        initComponents();
//        Locadora locadoraAtual = locadoraDao.get(1L); // to test
//        //addLocadora(locadoraAtual);
////        addCliente(locadoraAtual.getClientes().get(0));
//        addLocacao(locacaoCarroDao.getAllByLocadora(locadoraAtual).get(0));
        addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnGeral = new javax.swing.JPanel();
        pnConteudo = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtFormaPagamento = new javax.swing.JTextField();
        txtMulta = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        txtDataEntrega = new javax.swing.JTextField();
        txtDataLocacao = new javax.swing.JTextField();
        lblDataLocaaco = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblMulta = new javax.swing.JLabel();
        lblFormaPagamento = new javax.swing.JLabel();
        lblDataEntrega = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTipo.setText("Tipo do veículo");

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        lblModelo.setText("Modelo ");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        lblCor.setText("Cor");

        lblCliente.setText("Cliente");

        lblMarca.setText("Marca");

        lblPlaca.setText("Placa");

        txtMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultaActionPerformed(evt);
            }
        });

        lblDataLocaaco.setText("Data da Locação");

        lblValorTotal.setText("Valor Total");

        lblMulta.setText("Multa");

        lblFormaPagamento.setText("Forma Pagamento");

        lblDataEntrega.setText("Data da Entrega");

        lblTelefone.setText("Telefone");

        javax.swing.GroupLayout pnConteudoLayout = new javax.swing.GroupLayout(pnConteudo);
        pnConteudo.setLayout(pnConteudoLayout);
        pnConteudoLayout.setHorizontalGroup(
            pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConteudoLayout.createSequentialGroup()
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addComponent(lblFormaPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModelo)
                            .addComponent(lblCor)
                            .addComponent(lblMarca)
                            .addComponent(lblPlaca)
                            .addComponent(lblCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataLocaaco)
                            .addComponent(lblDataEntrega))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addComponent(lblMulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addComponent(lblValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnConteudoLayout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pnConteudoLayout.setVerticalGroup(
            pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConteudoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(8, 8, 8)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataLocaaco)
                    .addComponent(txtDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMulta)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormaPagamento))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnGeralLayout = new javax.swing.GroupLayout(pnGeral);
        pnGeral.setLayout(pnGeralLayout);
        pnGeralLayout.setHorizontalGroup(
            pnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGeralLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(pnConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        pnGeralLayout.setVerticalGroup(
            pnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGeralLayout.createSequentialGroup()
                .addComponent(pnConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDadosLocadoraLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDadosLocadoraLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDadosLocadoraLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDadosLocadoraLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDadosLocadoraLocacao().setVisible(true);
            }
        });
    }
    
    public void extraConfigs() {
        setTitle("FastVehicles | Locação veículo - " + locacaoAtual.getVeiculo().getModelo());
        //configs do frame - frames config
        setLocationRelativeTo(null);
        //coloca icone no jframe - insert icon on jframe
        URL url = getClass().getResource("/images/car-default-img.png");
        if(!(url == null)) {
            setIconImage(new ImageIcon(url).getImage());
        }
        
        //configs dos lbls e txts
        lblTipo.setFont(DesignApp.fonteGeral);
        lblModelo.setFont(DesignApp.fonteGeral);
        lblCor.setFont(DesignApp.fonteGeral);
        lblMarca.setFont(DesignApp.fonteGeral);
        lblPlaca.setFont(DesignApp.fonteGeral);
        lblCliente.setFont(DesignApp.fonteGeral);
        lblDataLocaaco.setFont(DesignApp.fonteGeral);
        lblDataEntrega.setFont(DesignApp.fonteGeral);
        lblValorTotal.setFont(DesignApp.fonteGeral);
        lblMulta.setFont(DesignApp.fonteGeral);
        lblFormaPagamento.setFont(DesignApp.fonteGeral);
        lblTelefone.setFont(DesignApp.fonteGeral);
        txtTipo.setFont(DesignApp.fonteGeral);
        txtModelo.setFont(DesignApp.fonteGeral);
        txtCor.setFont(DesignApp.fonteGeral);
        txtMarca.setFont(DesignApp.fonteGeral);
        txtPlaca.setFont(DesignApp.fonteGeral);
        txtCliente.setFont(DesignApp.fonteGeral);
        txtDataLocacao.setFont(DesignApp.fonteGeral);
        txtDataEntrega.setFont(DesignApp.fonteGeral);
        txtValorTotal.setFont(DesignApp.fonteGeral);
        txtMulta.setFont(DesignApp.fonteGeral);
        txtFormaPagamento.setFont(DesignApp.fonteGeral);
        txtTelefone.setFont(DesignApp.fonteGeral);
        
        txtTipo.setEditable(false);
        txtModelo.setEditable(false);
        txtCor.setEditable(false);
        txtMarca.setEditable(false);
        txtPlaca.setEditable(false);
        txtCliente.setEditable(false);
        txtDataLocacao.setEditable(false);
        txtDataEntrega.setEditable(false);
        txtValorTotal.setEditable(false);
        txtMulta.setEditable(false);
        txtFormaPagamento.setEditable(false);
        txtTelefone.setEditable(false);
        
        //coloca dados nos txts
        Veiculo veiculo = locacaoAtual.getVeiculo(); //pega veiculo 
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txtTipo.setText(veiculo.getTipo());
        txtModelo.setText(veiculo.getModelo());
        txtCor.setText(veiculo.getCor());
        txtMarca.setText(veiculo.getMarca());
        txtPlaca.setText(veiculo.getPlaca());
        txtCliente.setText(locacaoAtual.getCliente().getNome());
        txtDataLocacao.setText(sdf.format(locacaoAtual.getDataLocacao()));
        txtDataEntrega.setText(sdf.format(locacaoAtual.getDataEntrega()));
        txtValorTotal.setText(String.valueOf(locacaoAtual.getValorTotal()));
        txtMulta.setText(String.valueOf(locacaoAtual.getMulta()));
        txtFormaPagamento.setText(locacaoAtual.getFormaPagamento());
        txtTelefone.setText(locacaoAtual.getCliente().getTelefone());
        
          //update lang
        if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) {
            updateLangComponents();
        }
    }
    
    public void addLocacao(Locacao l) {
        this.locacaoAtual = l;
        extraConfigs();
    }
    
    //calcula valor total a partir das datas e do veiculo atual
    private double calcValorTotal(java.sql.Date dataEntrega, 
            java.sql.Date dataLocacao, Veiculo veiculo) {
        Calendar calEnt = Calendar.getInstance();
        calEnt.setTime(dataEntrega);
        Calendar calLoc = Calendar.getInstance();
        calLoc.setTime(dataLocacao);
        
        int[] dataEntArray = {calEnt.get(Calendar.DAY_OF_MONTH), 
            (calEnt.get(Calendar.MONTH) + 1), calEnt.get(Calendar.YEAR)}; //array com dados da data entrega
        
        int[] dataLocArray = {calLoc.get(Calendar.DAY_OF_MONTH), 
            (calLoc.get(Calendar.MONTH) + 1), calLoc.get(Calendar.YEAR)}; //array com dados da data entrega
                
        int dias = (dataEntArray[2] - dataLocArray[2])*365 //diferenca entre anos * 365
            + (dataEntArray[1] - dataLocArray[1])*30 //diferenca entre meses * 30
            + (dataEntArray[0] - dataLocArray[0]); //diferenca entre dias
        
//        System.out.println("dias " + dias);
        return dias * veiculo.getValorDiario(); //multiplica dias pelo valor diario
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDataEntrega;
    private javax.swing.JLabel lblDataLocaaco;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMulta;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnConteudo;
    private javax.swing.JPanel pnGeral;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDataEntrega;
    private javax.swing.JTextField txtDataLocacao;
    private javax.swing.JTextField txtFormaPagamento;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void resetaListenerCampos() {
        //faz nada (facilitar)
    }
    
     //window listener
    @Override
    public void windowOpened(WindowEvent e) {
        InstanceFrame.addFrame(this); //adiciona frame na lista de frames abertos
    }

    @Override
    public void windowClosing(WindowEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        InstanceFrame.removeFrame(this); //remove frame
    }

    @Override
    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    //update lang method
    @Override
    public void updateLangComponents() {
        
        if(IdiomaApp.idiomaAtual == IdiomaApp.INGLES) { //se idioma eh ingles
	    setTitle("FastVehicles | Rent Vehicle - " + locacaoAtual.getVeiculo().getModelo());
            lblTipo.setText("Type");
            lblModelo.setText("Model");
            lblCor.setText("Color");
            lblMarca.setText("Brand");
            lblPlaca.setText("Plate");
            lblCliente.setText("Client");
            lblTelefone.setText("Phone");
            lblDataLocaaco.setText("Location Date");
            lblDataEntrega.setText("Location Delivery");
            lblValorTotal.setText("Total value");
            lblMulta.setText("Ticket");
            lblFormaPagamento.setText("Payment");
            
	}else if(IdiomaApp.idiomaAtual == IdiomaApp.PORTUGUES) { //se for portugues
            setTitle("FastVehicles | Locação veículo - " + locacaoAtual.getVeiculo().getModelo());
            lblTipo.setText("Tipo");
            lblModelo.setText("Modelo");
            lblCor.setText("Cor");
            lblMarca.setText("Marca");
            lblPlaca.setText("Placa");
            lblCliente.setText("Cliente");
            lblTelefone.setText("Telefone");
            lblDataLocaaco.setText("Data da Locação");
            lblDataEntrega.setText("Data da Entrega");
            lblValorTotal.setText("Valor Total");
            lblMulta.setText("Multa");
            lblFormaPagamento.setText("Pagamento");
	}
   }
}
